// ** Styling Imports
import './globals.css'

// ** Component Imports
import Header from '@/components/Header'
import Footer from '@/components/Footer'

// ** Font Imports
import { DM_Sans } from 'next/font/google'
const dmSans = DM_Sans({ subsets: ['latin'] })

// ** Typescript Imports
import type { Metadata } from 'next'

// ** MetaData
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={dmSans.className}>
        <div className="min-h-screen flex flex-col items-center justify-between">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
