import Link from 'next/link'
import { ReactNode } from 'react'
import {
  Calculator,
  ArrowRightLeft,
  PiggyBank,
  TrendingUp,
  BarChart3,
  DollarSign,
  Percent,
  Building2,
  Scale,
  Clock,
  FileText,
  Landmark,
  CreditCard,
  Receipt,
  BadgeDollarSign,
  Briefcase,
  LineChart,
  Wallet,
  Banknote,
  Shield,
  BookOpen,
  Target,
} from 'lucide-react'

export type ToolCategory = 'calculators' | 'interactive-tools' | 'content-assets'
export type ToolStatus = 'live' | 'coming-soon'

export interface ToolData {
  slug: string
  name: string
  category: ToolCategory
  status: ToolStatus
  icon: React.ComponentType<{ className?: string }>
  shortDescription: string
  longDescription: string
  features: string[]
  faqs: { question: string; answer: ReactNode; schemaAnswer: string }[]
  seo: {
    title: string
    description: string
  }
  relatedTools: string[]
  relatedLoanProducts: string[]
}

export const categoryLabels: Record<ToolCategory, string> = {
  'calculators': 'Calculators',
  'interactive-tools': 'Interactive Tools',
  'content-assets': 'Content Assets',
}

export const toolsData: Record<string, ToolData> = {
  'loan-payment-calculator': {
    slug: 'loan-payment-calculator',
    name: 'Loan Payment Calculator',
    category: 'calculators',
    status: 'live',
    icon: Calculator,
    shortDescription: 'Calculate monthly payments, total interest, and amortization schedules for any business loan.',
    longDescription: 'Our free business loan payment calculator helps you estimate monthly payments, total interest costs, and view a complete amortization schedule. Compare different loan amounts, interest rates, and term lengths to find the financing structure that fits your budget.',
    features: ['Amortization schedule', 'Multiple payment frequencies', 'Interactive charts', 'Instant results'],
    faqs: [
      {
        question: 'How is the monthly loan payment calculated?',
        answer: <>The monthly payment is calculated using the standard amortization formula: M = P[r(1+r)^n] / [(1+r)^n - 1], where P is the loan amount, r is the monthly interest rate, and n is the total number of payments. This formula ensures each payment covers both interest and principal, with the interest portion decreasing over time as you pay down the balance. Our calculator handles this math automatically — just enter your <Link href="/business-loans/term-loans" className="text-theme-primary-light font-medium hover:underline">loan terms</Link> and see your results instantly.</>,
        schemaAnswer: 'The monthly payment is calculated using the standard amortization formula: M = P[r(1+r)^n] / [(1+r)^n - 1], where P is the loan amount, r is the monthly interest rate, and n is the total number of payments. This formula ensures each payment covers both interest and principal, with the interest portion decreasing over time as the balance is paid down.',
      },
      {
        question: 'What is an amortization schedule?',
        answer: <>An amortization schedule is a complete table showing every payment over the life of a loan, broken down into principal and interest components. Early payments consist mostly of interest, while later payments apply more toward the principal balance. This schedule helps you understand exactly how much of each payment goes toward reducing your debt versus paying interest charges. For <Link href="/business-loans/term-loans" className="text-theme-primary-light font-medium hover:underline">business term loans</Link>, understanding amortization is key to effective financial planning.</>,
        schemaAnswer: 'An amortization schedule is a complete table showing every payment over the life of a loan, broken down into principal and interest components. Early payments consist mostly of interest, while later payments apply more toward the principal balance. This schedule helps you understand exactly how much of each payment goes toward reducing your debt versus paying interest charges.',
      },
      {
        question: 'How does the payment frequency affect total interest paid?',
        answer: <>Choosing biweekly or weekly payments instead of monthly can reduce the total interest you pay over the life of the loan. With biweekly payments, you make 26 half-payments per year, which equals 13 full payments — one extra payment annually. This accelerates principal reduction and shortens the loan term. The savings can be significant on larger <Link href="/business-loans/term-loans" className="text-theme-primary-light font-medium hover:underline">business loans</Link>, potentially saving thousands in interest charges.</>,
        schemaAnswer: 'Choosing biweekly or weekly payments instead of monthly can reduce the total interest you pay over the life of the loan. With biweekly payments, you make 26 half-payments per year, which equals 13 full payments, one extra payment annually. This accelerates principal reduction and shortens the loan term, potentially saving thousands in interest charges.',
      },
      {
        question: 'What loan amounts and terms can I calculate?',
        answer: <>Our calculator supports loan amounts from $10,000 to $10,000,000, interest rates from 1% to 35%, and terms from 6 months to 25 years. You can toggle between monthly, biweekly, and weekly payment frequencies to see how each option affects your total cost. For personalized rates based on your business profile, you can <Link href="/get-started" className="text-theme-primary-light font-medium hover:underline">get your options</Link> with no impact to your credit score.</>,
        schemaAnswer: 'The calculator supports loan amounts from $10,000 to $10,000,000, interest rates from 1% to 35%, and terms from 6 months to 25 years. You can toggle between monthly, biweekly, and weekly payment frequencies to see how each option affects your total cost.',
      },
      {
        question: 'Is this calculator accurate for business loans?',
        answer: <>This calculator uses the same standard amortization formula that lenders use to determine payment schedules for <Link href="/business-loans/term-loans" className="text-theme-primary-light font-medium hover:underline">term loans</Link> and other fixed-rate products. However, actual loan terms may include origination fees, variable rates, or other factors that affect total cost. For a precise quote tailored to your situation, we recommend <Link href="/get-started" className="text-theme-primary-light font-medium hover:underline">speaking with a funding specialist</Link> at Quick Lenders.</>,
        schemaAnswer: 'This calculator uses the same standard amortization formula that lenders use to determine payment schedules for term loans and other fixed-rate products. However, actual loan terms may include origination fees, variable rates, or other factors that affect total cost. For a precise quote, speaking with a funding specialist is recommended.',
      },
    ],
    seo: {
      title: 'Business Loan Payment Calculator | Quick Lenders',
      description: 'Calculate your business loan payments, total interest, and amortization schedule. Free calculator with instant results — no signup required.',
    },
    relatedTools: ['factor-rate-to-apr-calculator', 'total-cost-of-capital-calculator', 'business-loan-comparison-tool'],
    relatedLoanProducts: ['term-loans', 'lines-of-credit', 'equipment-financing'],
  },
  'factor-rate-to-apr-calculator': {
    slug: 'factor-rate-to-apr-calculator',
    name: 'Factor Rate to APR Converter',
    category: 'calculators',
    status: 'live',
    icon: ArrowRightLeft,
    shortDescription: 'Convert factor rates to APR to understand the true annual cost of merchant cash advances and short-term loans.',
    longDescription: 'Factor rates can make expensive financing look affordable. Our free converter translates factor rates into APR so you can compare the true cost of merchant cash advances and short-term business loans against traditional financing options.',
    features: ['Factor rate to APR conversion', 'Total cost breakdown', 'Payment schedule', 'Cost comparison context'],
    faqs: [
      {
        question: 'What is a factor rate?',
        answer: <>A factor rate is a decimal number (typically between 1.1 and 1.5) used to calculate the total repayment amount on merchant cash advances and some short-term business loans. Unlike an interest rate, a factor rate is multiplied by the total borrowed amount to determine the fixed total repayment. For example, a $50,000 advance with a 1.30 factor rate means you repay $65,000 total. Because factor rates do not account for repayment timing, they can obscure the true cost — which is why converting to APR is important. Learn more about <Link href="/business-loans/term-loans" className="text-theme-primary-light font-medium hover:underline">term loan alternatives</Link> with transparent interest rates.</>,
        schemaAnswer: 'A factor rate is a decimal number (typically between 1.1 and 1.5) used to calculate the total repayment amount on merchant cash advances and some short-term business loans. It is multiplied by the total borrowed amount to determine the fixed total repayment. For example, a $50,000 advance with a 1.30 factor rate means you repay $65,000 total.',
      },
      {
        question: 'How do you convert a factor rate to APR?',
        answer: <>The simplified conversion formula is: APR = ((Factor Rate - 1) / Term in Years) x 100. For example, a 1.30 factor rate on a 6-month term equals approximately (0.30 / 0.5) x 100 = 60% APR. This conversion reveals the true annual cost, which is often dramatically higher than the factor rate suggests. Our <Link href="/tools/factor-rate-to-apr-calculator" className="text-theme-primary-light font-medium hover:underline">calculator</Link> handles this conversion instantly and also shows your total repayment, cost per dollar borrowed, and payment schedule.</>,
        schemaAnswer: 'The simplified conversion formula is: APR = ((Factor Rate - 1) / Term in Years) x 100. For example, a 1.30 factor rate on a 6-month term equals approximately (0.30 / 0.5) x 100 = 60% APR. This conversion reveals the true annual cost, which is often dramatically higher than the factor rate suggests.',
      },
      {
        question: 'Why is APR more useful than a factor rate?',
        answer: <>APR (Annual Percentage Rate) standardizes borrowing costs on an annual basis, making it possible to compare different financing products on equal footing. A factor rate of 1.20 might seem low, but if the repayment term is only 3 months, the APR could exceed 80%. Traditional <Link href="/business-loans/term-loans" className="text-theme-primary-light font-medium hover:underline">business loans</Link> and <Link href="/business-loans/lines-of-credit" className="text-theme-primary-light font-medium hover:underline">lines of credit</Link> quote rates as APR, making comparison straightforward. Always convert factor rates to APR before committing to any financing.</>,
        schemaAnswer: 'APR standardizes borrowing costs on an annual basis, making it possible to compare different financing products on equal footing. A factor rate of 1.20 might seem low, but if the repayment term is only 3 months, the APR could exceed 80%. Traditional business loans and lines of credit quote rates as APR, making comparison straightforward.',
      },
      {
        question: 'What is a typical factor rate for a merchant cash advance?',
        answer: <>Merchant cash advances typically carry factor rates between 1.10 and 1.50, with most falling in the 1.20 to 1.40 range. This translates to APRs that can range from 30% to over 150%, depending on the repayment term. While MCAs provide fast funding, the cost can be substantially higher than traditional options. If you qualify, a <Link href="/business-loans/term-loans" className="text-theme-primary-light font-medium hover:underline">business term loan</Link> or <Link href="/business-loans/lines-of-credit" className="text-theme-primary-light font-medium hover:underline">line of credit</Link> typically offers much lower effective rates.</>,
        schemaAnswer: 'Merchant cash advances typically carry factor rates between 1.10 and 1.50, with most falling in the 1.20 to 1.40 range. This translates to APRs that can range from 30% to over 150%, depending on the repayment term. While MCAs provide fast funding, the cost can be substantially higher than traditional term loans or lines of credit.',
      },
      {
        question: 'Can I use this calculator for any type of business financing?',
        answer: <>This calculator is specifically designed for financing products that use factor rates, including merchant cash advances, revenue-based financing, and some short-term business loans. If your financing uses a traditional interest rate, our <Link href="/tools/loan-payment-calculator" className="text-theme-primary-light font-medium hover:underline">loan payment calculator</Link> is the better tool. For help evaluating your overall financing options, <Link href="/get-started" className="text-theme-primary-light font-medium hover:underline">connect with our team</Link> for a no-obligation consultation.</>,
        schemaAnswer: 'This calculator is specifically designed for financing products that use factor rates, including merchant cash advances, revenue-based financing, and some short-term business loans. If your financing uses a traditional interest rate, a standard loan payment calculator would be the better tool.',
      },
    ],
    seo: {
      title: 'Factor Rate to APR Calculator | Quick Lenders',
      description: 'Convert factor rates to APR instantly. Understand the true cost of merchant cash advances and short-term loans with our free calculator.',
    },
    relatedTools: ['loan-payment-calculator', 'total-cost-of-capital-calculator', 'business-loan-comparison-tool'],
    relatedLoanProducts: ['term-loans', 'lines-of-credit'],
  },
  'total-cost-of-capital-calculator': {
    slug: 'total-cost-of-capital-calculator',
    name: 'Total Cost of Capital Calculator',
    category: 'calculators',
    status: 'coming-soon',
    icon: DollarSign,
    shortDescription: 'Calculate the complete cost of any financing option including fees, interest, and hidden charges.',
    longDescription: 'Understand the true total cost of your business financing by factoring in origination fees, closing costs, and all other charges beyond the stated interest rate.',
    features: ['All-in cost analysis', 'Fee breakdown', 'Effective rate calculation'],
    faqs: [],
    seo: { title: 'Total Cost of Capital Calculator | Quick Lenders', description: 'Calculate the true total cost of business financing including all fees and charges.' },
    relatedTools: ['loan-payment-calculator', 'factor-rate-to-apr-calculator'],
    relatedLoanProducts: ['term-loans', 'lines-of-credit'],
  },
  'break-even-calculator': {
    slug: 'break-even-calculator',
    name: 'Break-Even Calculator',
    category: 'calculators',
    status: 'live',
    icon: Target,
    shortDescription: 'Determine how many units or revenue you need to cover costs and start generating profit.',
    longDescription: 'Our free break-even calculator helps you determine exactly how many units you need to sell — or how much revenue you need to generate — to cover your fixed and variable costs. Visualize your profit zone with an interactive chart and make smarter pricing and financing decisions.',
    features: ['Break-even units & revenue', 'Contribution margin analysis', 'Interactive profit chart', 'Real-time calculations'],
    faqs: [
      {
        question: 'What is a break-even point?',
        answer: <>The break-even point is the number of units sold (or total revenue) at which your business covers all of its costs — both fixed and variable — with zero profit and zero loss. Every unit sold beyond the break-even point generates profit. Knowing your break-even point is essential when planning a new product launch, evaluating <Link href="/business-loans/term-loans" className="text-theme-primary-light font-medium hover:underline">business loan</Link> feasibility, or setting prices for your products and services.</>,
        schemaAnswer: 'The break-even point is the number of units sold (or total revenue) at which your business covers all of its costs, both fixed and variable, with zero profit and zero loss. Every unit sold beyond the break-even point generates profit. Knowing your break-even point is essential for planning product launches, evaluating loan feasibility, and setting prices.',
      },
      {
        question: 'How is the break-even point calculated?',
        answer: <>The break-even point in units is calculated by dividing your total fixed costs by the contribution margin per unit. The contribution margin is simply your selling price minus the variable cost per unit. For example, if your monthly fixed costs are $25,000, your price is $150, and your variable cost is $60 per unit, the contribution margin is $90, and you need to sell approximately 278 units to break even. Our <Link href="/tools/break-even-calculator" className="text-theme-primary-light font-medium hover:underline">calculator</Link> handles this math instantly.</>,
        schemaAnswer: 'The break-even point in units is calculated by dividing total fixed costs by the contribution margin per unit (selling price minus variable cost per unit). For example, if monthly fixed costs are $25,000, price is $150, and variable cost is $60, the contribution margin is $90 and you need to sell approximately 278 units to break even.',
      },
      {
        question: 'What is a contribution margin?',
        answer: <>The contribution margin is the amount each unit sold contributes toward covering your fixed costs and generating profit. It is calculated as the selling price minus the variable cost per unit. A higher contribution margin means you need fewer sales to break even. The contribution margin ratio — expressed as a percentage of the selling price — helps you understand how efficiently each dollar of revenue contributes to covering overhead. For businesses evaluating <Link href="/business-loans/equipment-financing" className="text-theme-primary-light font-medium hover:underline">equipment financing</Link>, improving contribution margin is a key lever.</>,
        schemaAnswer: 'The contribution margin is the amount each unit sold contributes toward covering fixed costs and generating profit, calculated as selling price minus variable cost per unit. A higher contribution margin means fewer sales are needed to break even. The contribution margin ratio, expressed as a percentage of selling price, shows how efficiently each revenue dollar covers overhead.',
      },
      {
        question: 'What counts as a fixed cost vs. a variable cost?',
        answer: <>Fixed costs remain constant regardless of how many units you sell — examples include rent, salaries, insurance, and <Link href="/business-loans/term-loans" className="text-theme-primary-light font-medium hover:underline">loan payments</Link>. Variable costs change directly with production volume — examples include raw materials, packaging, shipping, and sales commissions. Correctly categorizing your costs is critical for an accurate break-even analysis. If you are unsure, a good rule of thumb is: if the cost exists even when you sell zero units, it is fixed.</>,
        schemaAnswer: 'Fixed costs remain constant regardless of how many units you sell, such as rent, salaries, insurance, and loan payments. Variable costs change directly with production volume, such as raw materials, packaging, shipping, and sales commissions. If a cost exists even when you sell zero units, it is fixed.',
      },
      {
        question: 'How can break-even analysis help with financing decisions?',
        answer: <>Break-even analysis shows you exactly how much additional revenue a new investment or loan needs to generate before it becomes profitable. If you are considering a <Link href="/business-loans/term-loans" className="text-theme-primary-light font-medium hover:underline">term loan</Link> to fund expansion, add the loan payment to your fixed costs and recalculate — this tells you the minimum sales volume needed to cover the financing. You can also use our <Link href="/tools/loan-payment-calculator" className="text-theme-primary-light font-medium hover:underline">loan payment calculator</Link> to determine exact monthly payments before plugging them into this tool.</>,
        schemaAnswer: 'Break-even analysis shows how much additional revenue a new investment or loan needs to generate before it becomes profitable. By adding loan payments to fixed costs and recalculating, you can determine the minimum sales volume needed to cover financing costs.',
      },
    ],
    seo: {
      title: 'Break-Even Calculator | Free Business Tool | Quick Lenders',
      description: 'Calculate your break-even point in units and revenue. Visualize your profit zone with our free interactive chart — no signup required.',
    },
    relatedTools: ['loan-payment-calculator', 'roi-calculator', 'total-cost-of-capital-calculator'],
    relatedLoanProducts: ['term-loans', 'equipment-financing', 'lines-of-credit'],
  },
  'roi-calculator': {
    slug: 'roi-calculator',
    name: 'ROI Calculator',
    category: 'calculators',
    status: 'coming-soon',
    icon: TrendingUp,
    shortDescription: 'Measure the return on investment for business purchases, expansions, and financing decisions.',
    longDescription: 'Evaluate whether a business investment will generate positive returns by calculating ROI percentage, net profit, and payback period.',
    features: ['ROI percentage', 'Net profit estimate', 'Payback period'],
    faqs: [],
    seo: { title: 'ROI Calculator | Quick Lenders', description: 'Calculate return on investment for business decisions and financing.' },
    relatedTools: ['break-even-calculator', 'total-cost-of-capital-calculator'],
    relatedLoanProducts: ['term-loans', 'equipment-financing'],
  },
  'equipment-financing-calculator': {
    slug: 'equipment-financing-calculator',
    name: 'Equipment Financing Calculator',
    category: 'calculators',
    status: 'coming-soon',
    icon: Building2,
    shortDescription: 'Compare lease vs. buy options and calculate monthly payments for equipment purchases.',
    longDescription: 'Determine the best way to finance your equipment purchase by comparing lease and loan options, monthly payments, and total cost of ownership.',
    features: ['Lease vs. buy comparison', 'Monthly payment estimates', 'Tax benefit estimates'],
    faqs: [],
    seo: { title: 'Equipment Financing Calculator | Quick Lenders', description: 'Compare lease vs. buy options for business equipment financing.' },
    relatedTools: ['loan-payment-calculator', 'roi-calculator'],
    relatedLoanProducts: ['equipment-financing'],
  },
  'debt-service-coverage-calculator': {
    slug: 'debt-service-coverage-calculator',
    name: 'DSCR Calculator',
    category: 'calculators',
    status: 'coming-soon',
    icon: Scale,
    shortDescription: 'Calculate your Debt Service Coverage Ratio to understand your ability to service new debt.',
    longDescription: 'Lenders use DSCR to determine whether your business generates enough income to cover loan payments. Calculate yours to see where you stand before applying.',
    features: ['DSCR calculation', 'Lender threshold comparison', 'Income analysis'],
    faqs: [],
    seo: { title: 'DSCR Calculator | Quick Lenders', description: 'Calculate your Debt Service Coverage Ratio for business loan applications.' },
    relatedTools: ['loan-payment-calculator', 'total-cost-of-capital-calculator'],
    relatedLoanProducts: ['term-loans', 'asset-backed-loans'],
  },
  'prepayment-savings-calculator': {
    slug: 'prepayment-savings-calculator',
    name: 'Prepayment Savings Calculator',
    category: 'calculators',
    status: 'coming-soon',
    icon: PiggyBank,
    shortDescription: 'See how much you can save by making extra payments or paying off your loan early.',
    longDescription: 'Calculate the interest savings and time reduction from making additional principal payments on your business loan.',
    features: ['Interest savings', 'Time saved', 'Extra payment scenarios'],
    faqs: [],
    seo: { title: 'Prepayment Savings Calculator | Quick Lenders', description: 'Calculate how much you save by paying off your business loan early.' },
    relatedTools: ['loan-payment-calculator'],
    relatedLoanProducts: ['term-loans'],
  },
  'refinance-savings-calculator': {
    slug: 'refinance-savings-calculator',
    name: 'Refinance Savings Calculator',
    category: 'calculators',
    status: 'coming-soon',
    icon: Percent,
    shortDescription: 'Compare your current loan with refinance options to see if switching makes financial sense.',
    longDescription: 'Evaluate whether refinancing your existing business loan could lower your monthly payment, reduce total interest, or improve your cash flow.',
    features: ['Monthly payment comparison', 'Total interest savings', 'Break-even timeline'],
    faqs: [],
    seo: { title: 'Refinance Savings Calculator | Quick Lenders', description: 'Calculate potential savings from refinancing your business loan.' },
    relatedTools: ['loan-payment-calculator', 'total-cost-of-capital-calculator'],
    relatedLoanProducts: ['term-loans', 'lines-of-credit'],
  },
  'cash-flow-forecast-tool': {
    slug: 'cash-flow-forecast-tool',
    name: 'Cash Flow Forecast Tool',
    category: 'calculators',
    status: 'coming-soon',
    icon: LineChart,
    shortDescription: 'Project your business cash flow over the next 12 months with loan payments factored in.',
    longDescription: 'Forecast your monthly cash flow by entering revenue, expenses, and loan obligations to ensure your business can comfortably handle new financing.',
    features: ['12-month projection', 'Loan payment integration', 'Visual cash flow chart'],
    faqs: [],
    seo: { title: 'Cash Flow Forecast Tool | Quick Lenders', description: 'Project your business cash flow with loan payments included.' },
    relatedTools: ['loan-payment-calculator', 'debt-service-coverage-calculator'],
    relatedLoanProducts: ['term-loans', 'lines-of-credit'],
  },
  'business-loan-comparison-tool': {
    slug: 'business-loan-comparison-tool',
    name: 'Loan Comparison Tool',
    category: 'interactive-tools',
    status: 'coming-soon',
    icon: BarChart3,
    shortDescription: 'Compare up to 3 loan offers side by side to find the best option for your business.',
    longDescription: 'Enter the details of multiple loan offers and see a comprehensive side-by-side comparison including monthly payments, total cost, and effective rates.',
    features: ['Side-by-side comparison', 'Up to 3 offers', 'Total cost ranking'],
    faqs: [],
    seo: { title: 'Business Loan Comparison Tool | Quick Lenders', description: 'Compare multiple business loan offers side by side.' },
    relatedTools: ['loan-payment-calculator', 'factor-rate-to-apr-calculator'],
    relatedLoanProducts: ['term-loans', 'lines-of-credit'],
  },
  'funding-readiness-assessment': {
    slug: 'funding-readiness-assessment',
    name: 'Funding Readiness Assessment',
    category: 'interactive-tools',
    status: 'coming-soon',
    icon: Shield,
    shortDescription: 'Answer a few questions to see how prepared your business is for financing approval.',
    longDescription: 'Take a quick assessment to evaluate your business readiness for loan approval based on common lender criteria like revenue, time in business, and credit profile.',
    features: ['Readiness score', 'Improvement tips', 'Loan type recommendations'],
    faqs: [],
    seo: { title: 'Funding Readiness Assessment | Quick Lenders', description: 'Assess your business readiness for loan approval.' },
    relatedTools: ['business-loan-comparison-tool'],
    relatedLoanProducts: ['term-loans', 'lines-of-credit'],
  },
  'loan-type-finder': {
    slug: 'loan-type-finder',
    name: 'Loan Type Finder',
    category: 'interactive-tools',
    status: 'coming-soon',
    icon: Briefcase,
    shortDescription: 'Answer simple questions and get matched with the best loan type for your business needs.',
    longDescription: 'Not sure which type of business financing is right for you? Our loan type finder asks a few questions about your business and recommends the best product match.',
    features: ['Guided questionnaire', 'Personalized recommendations', 'Product explanations'],
    faqs: [],
    seo: { title: 'Loan Type Finder | Quick Lenders', description: 'Find the right business loan type for your needs.' },
    relatedTools: ['funding-readiness-assessment'],
    relatedLoanProducts: ['term-loans', 'lines-of-credit', 'equipment-financing'],
  },
  'invoice-factoring-calculator': {
    slug: 'invoice-factoring-calculator',
    name: 'Invoice Factoring Calculator',
    category: 'calculators',
    status: 'coming-soon',
    icon: Receipt,
    shortDescription: 'Calculate the cost and advance amount for factoring your outstanding invoices.',
    longDescription: 'Determine how much cash you can unlock from outstanding invoices and what the factoring fees will cost your business.',
    features: ['Advance amount estimate', 'Fee calculation', 'Net proceeds'],
    faqs: [],
    seo: { title: 'Invoice Factoring Calculator | Quick Lenders', description: 'Calculate invoice factoring costs and advance amounts.' },
    relatedTools: ['cash-flow-forecast-tool'],
    relatedLoanProducts: ['lines-of-credit'],
  },
  'mca-payback-calculator': {
    slug: 'mca-payback-calculator',
    name: 'MCA Payback Calculator',
    category: 'calculators',
    status: 'coming-soon',
    icon: CreditCard,
    shortDescription: 'Estimate daily or weekly MCA payments based on your revenue and holdback percentage.',
    longDescription: 'Calculate your expected merchant cash advance payments based on your daily credit card sales, holdback percentage, and total advance amount.',
    features: ['Daily payment estimate', 'Holdback calculation', 'Payback timeline'],
    faqs: [],
    seo: { title: 'MCA Payback Calculator | Quick Lenders', description: 'Calculate merchant cash advance repayment schedules.' },
    relatedTools: ['factor-rate-to-apr-calculator'],
    relatedLoanProducts: ['term-loans'],
  },
  'sba-loan-payment-calculator': {
    slug: 'sba-loan-payment-calculator',
    name: 'SBA Loan Payment Calculator',
    category: 'calculators',
    status: 'coming-soon',
    icon: Landmark,
    shortDescription: 'Estimate monthly payments for SBA 7(a) and 504 loans with typical SBA terms and rates.',
    longDescription: 'Calculate expected monthly payments for SBA loan programs using standard SBA terms, rates, and guarantee fee structures.',
    features: ['SBA 7(a) estimates', 'SBA 504 estimates', 'Guarantee fee calculation'],
    faqs: [],
    seo: { title: 'SBA Loan Payment Calculator | Quick Lenders', description: 'Calculate SBA 7(a) and 504 loan payment estimates.' },
    relatedTools: ['loan-payment-calculator'],
    relatedLoanProducts: ['term-loans'],
  },
  'business-valuation-estimator': {
    slug: 'business-valuation-estimator',
    name: 'Business Valuation Estimator',
    category: 'interactive-tools',
    status: 'coming-soon',
    icon: BadgeDollarSign,
    shortDescription: 'Get a rough estimate of your business value using common valuation multiples.',
    longDescription: 'Estimate your business value using industry-standard revenue and earnings multiples to understand your position for financing or exit planning.',
    features: ['Multiple valuation methods', 'Industry benchmarks', 'Range estimates'],
    faqs: [],
    seo: { title: 'Business Valuation Estimator | Quick Lenders', description: 'Estimate your business value for financing and exit planning.' },
    relatedTools: ['funding-readiness-assessment'],
    relatedLoanProducts: ['investment-banking', 'esop'],
  },
  'working-capital-calculator': {
    slug: 'working-capital-calculator',
    name: 'Working Capital Calculator',
    category: 'calculators',
    status: 'coming-soon',
    icon: Wallet,
    shortDescription: 'Calculate your working capital ratio and determine how much additional capital you need.',
    longDescription: 'Analyze your current assets versus current liabilities to understand your working capital position and identify financing gaps.',
    features: ['Working capital ratio', 'Gap analysis', 'Financing recommendations'],
    faqs: [],
    seo: { title: 'Working Capital Calculator | Quick Lenders', description: 'Calculate your working capital needs and ratio.' },
    relatedTools: ['cash-flow-forecast-tool', 'debt-service-coverage-calculator'],
    relatedLoanProducts: ['lines-of-credit', 'term-loans'],
  },
  'loan-affordability-calculator': {
    slug: 'loan-affordability-calculator',
    name: 'Loan Affordability Calculator',
    category: 'calculators',
    status: 'coming-soon',
    icon: Banknote,
    shortDescription: 'Determine the maximum loan amount your business can comfortably afford based on revenue.',
    longDescription: 'Enter your business revenue and expenses to calculate the maximum loan amount and monthly payment your business can handle without straining cash flow.',
    features: ['Max loan calculation', 'Affordability range', 'Payment-to-revenue ratio'],
    faqs: [],
    seo: { title: 'Loan Affordability Calculator | Quick Lenders', description: 'Calculate how much business loan you can afford.' },
    relatedTools: ['loan-payment-calculator', 'debt-service-coverage-calculator'],
    relatedLoanProducts: ['term-loans', 'lines-of-credit'],
  },
  'loan-document-checklist': {
    slug: 'loan-document-checklist',
    name: 'Loan Document Checklist',
    category: 'content-assets',
    status: 'coming-soon',
    icon: FileText,
    shortDescription: 'Get a personalized checklist of documents you need to prepare for your loan application.',
    longDescription: 'Select your loan type and business profile to receive a customized list of required documents, making your application process faster and smoother.',
    features: ['Personalized checklist', 'Download as PDF', 'Preparation tips'],
    faqs: [],
    seo: { title: 'Loan Document Checklist | Quick Lenders', description: 'Get a personalized document checklist for your business loan application.' },
    relatedTools: ['funding-readiness-assessment', 'loan-type-finder'],
    relatedLoanProducts: ['term-loans', 'lines-of-credit'],
  },
  'business-loan-glossary': {
    slug: 'business-loan-glossary',
    name: 'Business Loan Glossary',
    category: 'content-assets',
    status: 'coming-soon',
    icon: BookOpen,
    shortDescription: 'Look up definitions for common business financing terms, acronyms, and concepts.',
    longDescription: 'A comprehensive glossary of business lending terminology to help you navigate financing conversations with confidence.',
    features: ['Searchable terms', 'Plain-language definitions', 'Related concepts'],
    faqs: [],
    seo: { title: 'Business Loan Glossary | Quick Lenders', description: 'Definitions for business financing terms and concepts.' },
    relatedTools: ['loan-type-finder'],
    relatedLoanProducts: ['term-loans'],
  },
  'interest-rate-comparison-chart': {
    slug: 'interest-rate-comparison-chart',
    name: 'Interest Rate Comparison Chart',
    category: 'content-assets',
    status: 'coming-soon',
    icon: Clock,
    shortDescription: 'Compare typical interest rates across different business loan types and lender categories.',
    longDescription: 'An interactive chart comparing average interest rates for term loans, lines of credit, SBA loans, MCAs, and other financing products.',
    features: ['Rate ranges by product', 'Lender type comparison', 'Updated regularly'],
    faqs: [],
    seo: { title: 'Interest Rate Comparison Chart | Quick Lenders', description: 'Compare business loan interest rates across different products and lenders.' },
    relatedTools: ['loan-payment-calculator', 'factor-rate-to-apr-calculator'],
    relatedLoanProducts: ['term-loans', 'lines-of-credit'],
  },
}

export function getToolBySlug(slug: string): ToolData | undefined {
  return toolsData[slug]
}

export function getToolsByCategory(category: ToolCategory): ToolData[] {
  return Object.values(toolsData).filter((t) => t.category === category)
}

export function getLiveTools(): ToolData[] {
  return Object.values(toolsData).filter((t) => t.status === 'live')
}

export function getAllTools(): ToolData[] {
  return Object.values(toolsData)
}
